import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../themes/globals.css";
import "../themes/components.css";
import Layout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <body>
        <main>
          <Layout>{children}</Layout>
        </main>
      </body>
    </html>
  );
}
